### ISSUE TITLE
Why is USB not enabled for core1 example in OnEitherCore make file?

### ISSUE THREAD

**Issue by jancumps** [FreeRTOS/FreeRTOS-SMP-Demos#10]
build commands for core 0 example:
```
pico_add_extra_outputs(on_core_zero)
pico_enable_stdio_usb(on_core_zero 1)
```
for core 1 example, that last line is commented out:
```
pico_add_extra_outputs(on_core_one)
#pico_enable_stdio_usb(on_core_one 1)
```

https://github.com/FreeRTOS/FreeRTOS-SMP-Demos/blob/c84926adafd83830f75c3b59c85988a9898b7351/FreeRTOS/Demo/CORTEX_M0%2B_RP2040/OnEitherCore/CMakeLists.txt#L38

What is the reason for the difference ?

**Comment by RichardBarry** [comment]
Thanks for your question - I would be grateful if you can post it to the support forums here:  https://forums.freertos.org

**Comment by jancumps** [comment]
I will. Closing this issue
